/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface invoiceSchema {
  address: string;
  company: string;
  date: string;
  discount: number;
  item: {
    price: number;
    product: string;
    quantity: number;
    total?: number;
  }[];
  noInvoice: string;
  phoneNumber: string;
  profileId: number;
  publicUrlPdf: string;
  subTotal: number;
  total: number;
}
