/**
 * This file was automatically generated by joi-to-typescript
 * Do not modify this file manually
 */

export interface profileSchema {
  address: string;
  company: string;
  phoneNumber: string;
  publicUrlImage: string;
  userId: string;
}

export interface editProfileSchema {
  address?: string;
  company?: string;
  phoneNumber?: string;
  publicUrlImage?: string;
  userId: string;
}
